# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/master.xdc

# Block Designs: bd/design_5/design_5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5 || ORIG_REF_NAME==design_5} -quiet] -quiet

# IP: bd/design_5/ip/design_5_clk_wiz_0_0/design_5_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_clk_wiz_0_0 || ORIG_REF_NAME==design_5_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_PmodHYGRO_0_0/design_5_PmodHYGRO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_PmodHYGRO_0_0 || ORIG_REF_NAME==design_5_PmodHYGRO_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_microblaze_0_0/design_5_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_microblaze_0_0 || ORIG_REF_NAME==design_5_microblaze_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_gpio_0_0/design_5_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_axi_gpio_0_0 || ORIG_REF_NAME==design_5_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_uartlite_0_0/design_5_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_axi_uartlite_0_0 || ORIG_REF_NAME==design_5_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_mdm_1_0/design_5_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_mdm_1_0 || ORIG_REF_NAME==design_5_mdm_1_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_rst_clk_wiz_0_100M_0/design_5_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_5_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_microblaze_0_axi_periph_0/design_5_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_5_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_xbar_0/design_5_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_xbar_0 || ORIG_REF_NAME==design_5_xbar_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_dlmb_v10_0/design_5_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_dlmb_v10_0 || ORIG_REF_NAME==design_5_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_ilmb_v10_0/design_5_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_ilmb_v10_0 || ORIG_REF_NAME==design_5_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_dlmb_bram_if_cntlr_0/design_5_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_5_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_ilmb_bram_if_cntlr_0/design_5_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_5_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_lmb_bram_0/design_5_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_lmb_bram_0 || ORIG_REF_NAME==design_5_lmb_bram_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_TOP_0_0/design_5_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_5_TOP_0_0 || ORIG_REF_NAME==design_5_TOP_0_0} -quiet] -quiet

# XDC: bd/design_5/design_5_ooc.xdc
