# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    {c:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/new_HYGRO_BD_HDL_2.srcs/sources_1/bd/design_3_new/ipshared/4868}
    {c:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/new_HYGRO_BD_HDL_2.srcs/sources_1/bd/design_3_new/ipshared/ec67/hdl}
  } {
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_clk_wiz_0_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_microblaze_0_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_PmodHYGRO_0_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_axi_gpio_0_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_axi_gpio_1_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_axi_uartlite_0_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_mdm_1_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_rst_clk_wiz_0_100M_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_xbar_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_dlmb_v10_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_ilmb_v10_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_dlmb_bram_if_cntlr_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_ilmb_bram_if_cntlr_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_lmb_bram_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_PWM_1_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/realtime/design_3_new_s00_mmu_0_stub.vhdl}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/new_HYGRO_BD_HDL_2.srcs/sources_1/bd/design_3_new/synth/design_3_new.vhd}
      {C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/new_HYGRO_BD_HDL_2.srcs/sources_1/bd/design_3_new/hdl/design_3_new_wrapper.vhd}
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_3_new_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Ryan/Desktop/Spring 2019/ECE351/FinalProject/ECE-351-Group-1/BlockDesign_HYGRO_FOLDER/.Xil/Vivado-21380-Ryan-pc/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
