# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/new_design_1/new_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1 || ORIG_REF_NAME==new_design_1} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_clk_wiz_0_0/new_design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_clk_wiz_0_0 || ORIG_REF_NAME==new_design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_microblaze_0_0/new_design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_microblaze_0_0 || ORIG_REF_NAME==new_design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_axi_uartlite_0_0/new_design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_axi_uartlite_0_0 || ORIG_REF_NAME==new_design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_PmodHYGRO_0_0/new_design_1_PmodHYGRO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_PmodHYGRO_0_0 || ORIG_REF_NAME==new_design_1_PmodHYGRO_0_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_mdm_1_0/new_design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_mdm_1_0 || ORIG_REF_NAME==new_design_1_mdm_1_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_rst_clk_wiz_0_100M_0/new_design_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==new_design_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_microblaze_0_axi_periph_0/new_design_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==new_design_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_xbar_0/new_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_xbar_0 || ORIG_REF_NAME==new_design_1_xbar_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_dlmb_v10_0/new_design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_dlmb_v10_0 || ORIG_REF_NAME==new_design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_ilmb_v10_0/new_design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_ilmb_v10_0 || ORIG_REF_NAME==new_design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_dlmb_bram_if_cntlr_0/new_design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==new_design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_ilmb_bram_if_cntlr_0/new_design_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==new_design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/new_design_1/ip/new_design_1_lmb_bram_0/new_design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==new_design_1_lmb_bram_0 || ORIG_REF_NAME==new_design_1_lmb_bram_0} -quiet] -quiet

# XDC: bd/new_design_1/new_design_1_ooc.xdc
